language: python

python:
  # - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# matrix:
#   include:
#     - python: "3.7"
#       dist: xenial
#       sudo: required

services:
  - xvfb


install:
  - pip install --upgrade pip
  - pip install -U matplotlib==2.2.3 # Needed because Travis CI pulls 3.0.2 even though it doesn't work with Python 2.7
  - pip install -U scipy==1.1.0 # Compatible with Python 2 and 3
  - pip install lytest  # For XOR testing
  - pip install -U rectpack
  - python setup.py install

script:
  - python ./phidl/phidl_tutorial_example.py
  - pytest tests
